apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "koh.fullname" . }}-beat
  labels:
    {{- include "koh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.beat.replicaCount }}
  selector:
    matchLabels:
      {{- include "koh.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        {{- include "koh.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: beat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - koh.celery_worker:celery_app
            - beat
            - --loglevel=info
            - --schedule=/tmp/celerybeat-schedule
          envFrom:
            - configMapRef:
                name: {{ include "koh.fullname" . }}-config
            - secretRef:
                name: {{ include "koh.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources.beat | nindent 12 }}
