apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "koh.fullname" . }}-worker
  labels:
    {{- include "koh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "koh.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "koh.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - koh.celery_worker:celery_app
            - worker
            - --loglevel=info
            - --pool={{ .Values.worker.pool }}
            - --concurrency={{ .Values.worker.concurrency }}
          envFrom:
            - configMapRef:
                name: {{ include "koh.fullname" . }}-config
            - secretRef:
                name: {{ include "koh.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.env.dataDir }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "koh.sharedVolumeClaimName" . }}
