apiVersion: v1
kind: Secret
metadata:
  name: {{ include "koh.fullname" . }}-secret
  labels:
    {{- include "koh.labels" . | nindent 4 }}
type: Opaque
stringData:
  KOH_ADMIN_USERNAME: {{ .Values.env.adminUsername | quote }}
  KOH_ADMIN_PASSWORD: {{ .Values.env.adminPassword | quote }}
  SECRET_KEY: {{ .Values.env.secretKey | quote }}
  DATABASE_URL: {{ .Values.env.databaseUrl | quote }}
  REDIS_URL: {{ .Values.env.redisUrl | quote }}
