{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "koh.fullname" . }}
  {{- with .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "koh.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "koh.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.monitoring.prometheus.port }}
      path: {{ .Values.monitoring.prometheus.path }}
      interval: {{ .Values.monitoring.prometheus.interval }}
      scrapeTimeout: {{ .Values.monitoring.prometheus.scrapeTimeout }}
{{- end }}
